### ISSUE TITLE
Job spec is empty in `describe` output

### ISSUE THREAD

**Issue by simonwo** [bacalhau-project/bacalhau#1756]
As of v0.3.17, the output of `bacalhau describe` no longer shows the submitted job spec. E.g.
```
% bacalhau docker run ubuntu date
Job successfully submitted. Job ID: cd0ac6a7-4707-4985-baef-462d05d53aee
Checking job status... (Enter Ctrl+C to exit at any time, your job will continue running):

	    Communicating with the network  ................ done ✅  0.0s
	       Creating job for submission  ................ done ✅  0.0s
	       Finding node(s) for the job  ................ done ✅  0.0s
	                   Running the job  ................ done ✅  0.0s
	   Job finished, verifying results  ................ done ✅  0.0s

To download the results, execute:
  bacalhau get cd0ac6a7-4707-4985-baef-462d05d53aee

To get more details about the run, execute:
  bacalhau describe cd0ac6a7-4707-4985-baef-462d05d53aee
```

```
% bacalhau describe cd0ac6a7-4707-4985-baef-462d05d53aee
APIVersion: ""
Metadata:
  CreatedAt: "2023-01-23T23:18:11.487225787Z"
  ID: cd0ac6a7-4707-4985-baef-462d05d53aee
Spec:
  Deal: {}
  Docker: {}
  ExecutionPlan: {}
  Language:
    JobContext: {}
  Network:
    Type: None
  Resources:
    GPU: ""
  Sharding: {}
  Wasm:
    EntryModule: {}
Status:
  JobState:
    Nodes:
      QmUDAXvv31WPZ8U9CzuRTMn9iFGiopGE7rHiah1X8a6PkT:
        Shards:
          "0":
            ExecutionId: e-62fe6b2c-b144-4b4f-9f2b-80d9a4951752
            NodeId: QmUDAXvv31WPZ8U9CzuRTMn9iFGiopGE7rHiah1X8a6PkT
            PublishedResults: {}
            State: Cancelled
            VerificationResult: {}
      QmXaXu9N5GNetatsvwnTfQqNtSeKAD6uCmarbh3LMRYAcF:
        Shards:
          "0":
            ExecutionId: e-acfdd5aa-e4cc-4d4d-9ee2-f83ade1322fd
            NodeId: QmXaXu9N5GNetatsvwnTfQqNtSeKAD6uCmarbh3LMRYAcF
            PublishedResults: {}
            State: Cancelled
            VerificationResult: {}
      QmdZQ7ZbhnvWY1J12XYKGHApJ6aufKyLNSvf8jZBrBaAVL:
        Shards:
          "0":
            ExecutionId: e-eaccde19-075a-40ea-a3dd-aa5b7daa98b9
            NodeId: QmdZQ7ZbhnvWY1J12XYKGHApJ6aufKyLNSvf8jZBrBaAVL
            PublishedResults:
              CID: QmWqRhKGFqE8j1a1ZqLa5cLDZ8WNq4LRw7UVzVbZTKWJuM
              Name: job-cd0ac6a7-4707-4985-baef-462d05d53aee-shard-0-host-QmdZQ7ZbhnvWY1J12XYKGHApJ6aufKyLNSvf8jZBrBaAVL
              StorageSource: IPFS
            RunOutput:
              exitCode: 0
              runnerError: ""
              stderr: ""
              stderrtruncated: false
              stdout: |
                Mon Jan 23 23:18:11 UTC 2023
              stdouttruncated: false
            State: Completed
            VerificationResult:
              Complete: true
              Result: true
  Requester:
    RequesterNodeID: QmYgxZiySj3MRkwLSL4X2MF5F9f2PMhAE3LV49XkfNL1o3
```

Notice that the Docker section is empty... it should at least be showing the image and entrypoint fields.
