### ISSUE TITLE
Job blocked until devstack closed, then shows routing failure error

### ISSUE THREAD

**Issue by rossjones** [bacalhau-project/bacalhau#2399]
When running the following command 

```shell
/bacalhau docker run keinos/sqlite3:3.41.2  \
    -i src=ipfs://QmYhtygPS9b81KyUYtv4VXkXzH5xkRycjqG18v3fWzZjJt,dst=/inputs/data.db \
     -- "ls /inputs"
``` 
against a local devstack with --public-ipfs (and LOG_LEVEL=debug).

The command runs, but stays InProgress until it eventually times out. The state is 

```yaml 
ComputeReference: e-363b5478-8804-4424-b904-db245138d112
JobID: 27ca9c11-2cc1-4c15-878b-a4cc3f22958b
NodeId: QmaS5iBuAuhN2acsCJqLxThJFseXnfErm1NRyXwka7N1ic
State: BidAccepted
```

And the events for that job show as 

```yaml
History:
- ComputeReference: e-363b5478-8804-4424-b904-db245138d112
  ExecutionState:
    New: AskForBid
  JobID: 27ca9c11-2cc1-4c15-878b-a4cc3f22958b
  NewVersion: 1
  NodeID: QmaS5iBuAuhN2acsCJqLxThJFseXnfErm1NRyXwka7N1ic
  Time: "2023-04-24T11:45:23.365876+01:00"
  Type: ExecutionLevel
- ComputeReference: e-363b5478-8804-4424-b904-db245138d112
  ExecutionState:
    New: AskForBidAccepted
    Previous: AskForBid
  JobID: 27ca9c11-2cc1-4c15-878b-a4cc3f22958b
  NewVersion: 2
  NodeID: QmaS5iBuAuhN2acsCJqLxThJFseXnfErm1NRyXwka7N1ic
  Time: "2023-04-24T11:45:23.365876+01:00"
  Type: ExecutionLevel
- ComputeReference: e-363b5478-8804-4424-b904-db245138d112
  ExecutionState:
    New: BidAccepted
    Previous: AskForBidAccepted
  JobID: 27ca9c11-2cc1-4c15-878b-a4cc3f22958b
  NewVersion: 3
  NodeID: QmaS5iBuAuhN2acsCJqLxThJFseXnfErm1NRyXwka7N1ic
  Time: "2023-04-24T11:45:25.15106+01:00"
  Type: ExecutionLevel
```

When patience wears thin and you sigint (ctrl-c) the devstack process it shows the error that it seems to have been stuck on. Have so far seem two different errors.

```
# Error 1
ERR pkg/requester/scheduler_state.go:107 > [transitionJobState] failed to find enough nodes 
to retry error="not enough nodes to run job. requested: 1, available: 0" 
    [NodeID:QmcpdKCQ]
ERR pkg/requester/scheduler.go:518 > error completing job acfdea4e-f1ad-4751-b981-f65ba5c709ca 
    error="not enough nodes to run job. requested: 1, available: 0; 
    node QmcsipgQ9uKhFgThAJeTrwm2yMXz2bspejV2sVt8JHpDJv failed due to: compute.AskForBidRequest: 
    failed to open stream to peer QmcsipgQ9uKhFgThAJeTrwm2yMXz2bspejV2sVt8JHpDJv: failed to find 
    peers: routing failure: provided addrs for different peer" [NodeID:QmcpdKCQ] 
[stack:[
    {"func":"(*BaseScheduler).stopJob","line":"518","source":"scheduler.go"},
    {"func":"(*BaseScheduler).checkForFailedExecutions.func1","line":"100","source":"scheduler_state.go"},
    {"func":"(*BaseScheduler).checkForFailedExecutions","line":"109","source":"scheduler_state.go"},
    {"func":"(*BaseScheduler).transitionJobStateLockFree","line":"43","source":"scheduler_state.go"},
    {"func":"(*BaseScheduler).transitionJobState","line":"22","source":"scheduler_state.go"},
    {"func":"(*BaseScheduler).handleExecutionFailure","line":"510","source":"scheduler.go"},
    {"func":"(*BaseScheduler).doNotifyAskForBid","line":"177","source":"scheduler.go"},        
    {"func":"goexit","line":"1172","source":"asm_arm64.s"}]]
```

and 

```
# Error 2 
ERR pkg/compute/executor.go:113 > failed to run execution 
    error="failed to copy /inputs/data.db to volume: failed to write to 
    '/var/folders/xv/mmq61h251nd7lw9yhr6x67yr0000gn/T/bacalhau-ipfs280919020/QmYhtygPS9b81KyUYtv4VXkXzH5xkRycjqG18v3fWzZjJt': 
    failed to fetch all nodes" 
    [NodeID:QmaS5iBu] 
    [execution:e-363b5478-8804-4424-b904-db245138d112] 
    [job:27ca9c11-2cc1-4c15-878b-a4cc3f22958b]
ERR pkg/compute/executor.go:238 > Running execution e-363b5478-8804-4424-b904-db245138d112 failed   
    error="failed to copy /inputs/data.db to volume: failed to write to 
   '/var/folders/xv/....T/bacalhau-ipfs280919020/QmYhtygPS9b81KyUYtv4VXkXzH5xkRycjqG18v3fWzZjJt': 
    failed to fetch all nodes" 
    [NodeID:QmaS5iBu] 
    [execution:e-363b5478-8804-4424-b904-db245138d112] 
    [job:27ca9c11-2cc1-4c15-878b-a4cc3f22958b]
....
 ERR pkg/transport/bprotocol/callback_proxy.go:108 > 
    compute.ComputeError: failed to open stream to peer QmYaUykMeZcySU99Xw3V8CecqhoWp14Dc7E2MnVFsKwqSA 
    error="failed to find peers: routing failure: provided addrs for different peer" 
    [NodeID:QmaS5iBu] 
    [execution:e-363b5478-8804-4424-b904-db245138d112] 
    [job:27ca9c11-2cc1-4c15-878b-a4cc3f22958b] 
    [stack:[
        {"func":"proxyCallbackRequest","line":"108","source":"callback_proxy.go"},
        {"func":"(*CallbackProxy).OnComputeFailure","line":"69","source":"callback_proxy.go"},
        {"func":"(*BaseExecutor).handleFailure","line":"248","source":"executor.go"},
        {"func":"(*BaseExecutor).Run.func2","line":"70","source":"executor.go"},
        {"func":"(*BaseExecutor).Run","line":"114","source":"executor.go"},
        {"func":"(*ExecutorBuffer).doRun.func1","line":"139","source":"executor_buffer.go"},        {"func":"goexit","line":"1172","source":"asm_arm64.s"}]
]
```
