### ISSUE TITLE
Error for submitting job with networking is very confusing

### ISSUE THREAD

**Issue by aronchick** [bacalhau-project/bacalhau#2544]
Job yaml:
```
Job:
  APIVersion: V1beta1
  Spec:
    Deal:
      Concurrency: 4
    Docker:
      Entrypoint:
        - /bin/bash
        - -c
        - python3 /process.py aperitivo_logs.log.1 archive-bucket "SELECT * FROM log_data WHERE message LIKE '%[SECURITY]%' ORDER BY '@timestamp'"
      Image: docker.io/bacalhauproject/duckdb-log-processor:v1.0.6
    Engine: Docker
    Network:
      Type: Full
    inputs:
      - Name: file:///var/log/logs_to_process
        SourcePath: /var/log/logs_to_process
        StorageSource: LocalDirectory
        path: /var/log/logs_to_process
```

Error:
```
❯ cat job.yaml | bacalhau create
Job successfully submitted. Job ID: 14745a35-7b29-4b81-bf00-5acabf086200
Checking job status... (Enter Ctrl+C to exit at any time, your job will continue running):

	Communicating with the network  ................  done ✅  0.1s
	   Creating job for submission  ................  done ✅  0.0s
	   Job waiting to be scheduled  ................  err  ❌  0.0s

Error submitting job: job rejected: command `/terraform_node/apply-http-allowlist.sh` returned non-zero exit code 1
Job Results By Node:
```
