### ISSUE TITLE
bacalhau create doesn't support reading from stdin

### ISSUE THREAD

**Issue by lukemarsden** [bacalhau-project/bacalhau#2608]
bacalhau create promises that it can read from stdin, with this --help example:
```
  # Create a new job from an already executed job
  bacalhau describe 6e51df50 | bacalhau create -
```
yet when trying:
```
echo "APIVersion: V1beta1
Metadata:
  CreatedAt: "0001-01-01T00:00:00Z"
  Requester: {}
Spec:
  Deal:
    Concurrency: 1
  Docker:
    Entrypoint:
    - echo
    - hello
    Image: ubuntu
  Engine: Docker
  Language:
    JobContext: {}
  Network:
    Type: None
  PublisherSpec:
    Type: Estuary
  Resources:
    GPU: ""
  Timeout: 1800
  Verifier: Noop
  Wasm:
    EntryModule: {}
  outputs:
  - Name: outputs
    StorageSource: IPFS
    path: /outputs
" |bacalhau create -
```
alas, it does not:
```
Error opening file: open -: no such file or directory
```
