### ISSUE TITLE
GPU issues on v1.1.0

### ISSUE THREAD

**Issue by lukemarsden** [bacalhau-project/bacalhau#2858]
Couple of issues:
* when specifying JobSpecs not via the new EngineSpec field, but the older Docker field, GPU scheduling failed, said 0 nodes available (even though that wasn't true)
* when using the new EngineSpec with `docker` subfield, GPU containers would start but hang for a while and then exit with error code 137

The same containers (using the old style jobspec) worked on 1.0.3

Tested on two different GPUs (a 4090 and A100 - the latter on lambdalabs.com), same behavior on both, Ubuntu 22.04 and 20.04 respectively, with nvidia docker drivers installed according to the nvidia docs, and docker installed from the instructions on the docker docs

**Comment by lukemarsden** [comment]
old spec (breaks scheduling on 1.1.0): https://github.com/bacalhau-project/lilypad-module-sdxl/blob/da4221cc4110d1e919cb490e5262e6e219433994/lilypad_module.json.tmpl
new spec (weird container hanging and exiting with exit code 137 after logging nothing): https://github.com/bacalhau-project/lilypad-module-sdxl/blob/43079c3979aaea9d6490749f818facfe05018cfa/lilypad_module.json.tmpl

**Comment by rossjones** [comment]
I tried this on production:

```
bacalhau docker run --gpu=1  \
 quay.io/lukemarsden/sdxl:v0.9-lilypad1-v2 \
 -e PROMPT="question mark floating in space" 
 -e RANDOM_SEED=42 \
 -e OUTPUT_DIR=/outputs/ \
 -e HF_HUB_OFFLINE=1 \
"python3 inference.py 2>/dev/null"
```
and then `bacalhay describe 062b4b89`  tells me it is running and gives me this as a spec.

```yaml
Spec:
  Deal:
    Concurrency: 1
  Docker: {}
  EngineSpec:
    Params:
      Entrypoint: null
      EnvironmentVariables:
      - PROMPT=question mark floating in space
      - RANDOM_SEED=42
      - OUTPUT_DIR=/outputs/
      - HF_HUB_OFFLINE=1
      Image: quay.io/lukemarsden/sdxl:v0.9-lilypad1-v2
      Parameters:
      - python3 inference.py 2>/dev/null
      WorkingDirectory: ""
    Type: docker
  Network:
    Type: None
  Outputs:
  - Name: outputs
    Path: /outputs
  PublisherSpec:
    Type: ipfs
  Resources:
    GPU: "1"
  Timeout: 1800
  Wasm:
    EntryModule: {}
```

Job didn't finish after 10m though, is it a particularly long job or is it possibly stuck?
