### ISSUE TITLE
Running a job with input sources against v2 api returns unexpected error

### ISSUE THREAD

**Issue by frrist** [bacalhau-project/bacalhau#3275]
Steps to reproduce:
job.yaml:
```yaml
name: A Simple Docker Job
type: batch
count: 1
tasks:
  - name: My main task
    inputsources:
      - source:
          type: urlDownload
          params:
            url: https://gist.githubusercontent.com/enricorotundo/990f0ad01a50d08dfb580e4ad404870e/raw/aa6934257351a0da93f1e740c72f27128590cebc/foo_data.txt
        target: /inputs
    engine:
      type: docker
      params:
        Image: ubuntu:latest
        Entrypoint:
          - /bin/bash
        Parameters:
          - cat /inputs/foo_data.txt > /outputs/foo_data.txt
```
command:
```bash
bacalhau job run job.yaml
```
error:
```bash
bacalhau job run job.yaml
Job successfully submitted. Job ID: j-dddd5135-0cf3-4498-ac59-c8a8f018e7bb
Checking job status... (Enter Ctrl+C to exit at any time, your job will continue running):

	Communicating with the network  ................  done ✅  0.0s
	   Creating job for submission  ...  🐟      ...           0.5s
Error submitting job: Error getting job: Get "http://bootstrap.production.bacalhau.org:1234/api/v1/orchestrator/jobs/j-dddd5135-0cf3-4498-ac59-c8a8f018e7bb": dial tcp 35.245.161.250:1234: co	   Creating job for submission  ...       🐠 ...           0.6sfailed to print job execution: failed getting job executions: Get "http://bootstrap.production.bacalhau.org:1234/api/v1/orchestrator/jobs/j-dddd5135-0cf3-4498-ac59-c8a8f018e7bb/executions": dial tcp 35.245.161.250:1234: connect: connection refused
```
