### ISSUE TITLE
Job fails when Input doesn't have schema?

### ISSUE THREAD

**Issue by aronchick** [bacalhau-project/bacalhau#3566]
Possible failure?

```
    Inputs:
    - Name: /Users/christoph/dev/Bacalhau/go-wasm/inputs
      Path: /inputs
      SourcePath: /Users/christoph/dev/Bacalhau/go-wasm/inputs
      StorageSource: localDirectory
    Network:
      Type: None
    Outputs:
    - Name: outputs
      Path: /outputs
    PublisherSpec:
      Type: ipfs
    Resources:
      GPU: ""
    Timeout: 1800
    Wasm:
      EntryModule: {}
```

Works:
```
    Inputs:
    - Name: file:///Users/christoph/dev/Bacalhau/go-wasm/inputs
      Path: /inputs
      SourcePath: /Users/christoph/dev/Bacalhau/go-wasm/inputs
      StorageSource: localDirectory
    Network:
      Type: None
    Outputs:
    - Name: outputs
      Path: /outputs
    PublisherSpec:
      Type: ipfs
    Resources:
      GPU: ""
    Timeout: 1800
    Wasm:
      EntryModule: {}
```

**Comment by simonwo** [comment]
Both of these fail for me with:
```
error executing job: failed to decode wasm engine spec. unhandled storage spec: unknown
```
Which is due to an empty `EntryModule`. Do you have a complete job spec example?

**Comment by simonwo** [comment]
This works just fine for me with `bacalhau serve --node-type=requester,compute --peer=none --allow-listed-local-paths=/Users/simon/bacalhau,/Users/simon/bacalhau/testdata/wasm/test` followed by `bacalhau create`:
```yaml
APIVersion:
Spec:
  Engine: wasm
  Inputs:
  - Name: /Users/simon/bacalhau
    Path: /inputs
    SourcePath: /Users/simon/bacalhau
    StorageSource: localDirectory
  Network:
    Type: None
  Outputs:
  - Name: outputs
    Path: /outputs
  PublisherSpec:
    Type: ipfs
  Resources:
    GPU: ""
  Timeout: 1800
  Wasm:
    EntryModule:
      Name: hello
      Path: /prog
      SourcePath: /Users/simon/bacalhau/testdata/wasm/test
      StorageSource: localDirectory
```
