### ISSUE TITLE
Setting TLS server key doesn't work

### ISSUE THREAD

**Issue by simonwo** [bacalhau-project/bacalhau#3633]
The [TLS docs](https://docs.bacalhau.org/running-node/configuring-tls/#self-signed-certificates) say:
> If you are using a configuration file, you can set the values inNode.ServerAPI.TLS.ServerCertificate and Node.ServerAPI.TLS.ServerTLSKey instead.

And if we look at the defaults, we see:
```
% bacalhau config default | grep 'ServerAPI' -A11
    ServerAPI:
        Host: 0.0.0.0
        Port: 1234
        ClientTLS:
            UseTLS: false
            CACert: ""
            Insecure: false
        TLS:
            AutoCert: ""
            AutoCertCachePath: ""
            ServerCertificate: ""
            ServerTLSKey: ""
```

But:
```
% bacalhau config set node.serverapi.tls.servertlskey ...
Error: invalid configuration key "node.serverapi.tls.servertlskey": not found
```
And this does not have the desired effect i.e. TLS is not enabled:
```
echo 'Node.ServerAPI.TLS.ServerTLSKey: ...' >> $BACALHAU_DIR/config.yaml
```

But this works:
```
% bacalhau config set node.serverapi.tls.serverkey ...
% cat $BACALHAU_DIR/config.yaml
node:
    serverapi:
        tls:
            serverkey: ...
```

So it looks like whilst the `default` command will respect the tag name defined on the config structure, the rest of the config system only pays attention to the Go field name and not the defined YAML tag.
