### ISSUE TITLE
Running `bacalhau get` fails to merge results when downloading

### ISSUE THREAD

**Issue by frrist** [bacalhau-project/bacalhau#3677]
Steps to reproduce:
1. Run this job:
```yaml
Name: Docker Job with Output
Type: batch
Namespace: default
Count: 2
Tasks:
  - Name: main
    Engine:
      Type: docker
      Params:
        Image: ubuntu:latest
        Entrypoint:
          - /bin/bash
        Parameters:
          - -c
          - dd if=/dev/urandom of=/output_custom/output.txt bs=1M count=1

    Publisher:
      Type: local
    ResultPaths:
      - Name: output_custom
        Path: /output_custom
```
2. Run `bacalhau get`
```bash
bacalhau get j-1cbabf4e-3ac9-4496-adb5-34d43248a308
Fetching results of job 'j-1cbabf4e-3ac9-4496-adb5-34d43248a308'...
error downloading job: cannot merge results as output already exists: /home/frrist/workspace/src/github.com/bacalhau-project/bacalhau/job-j-1cbabf4e/output_custom/output.txt. Try --raw to download raw results instead of merging them
```
3. Observe the resulting download
```bash
tree job-j-1cbabf4e
job-j-1cbabf4e
├── exitCode
├── output_custom
│   └── output.txt
├── raw
│   ├── 34.150.138.100_6001_e-a57e7662-07fd-41bd-9fa4-c0d0b5d14f94
│   │   ├── exitCode
│   │   ├── output_custom
│   │   │   └── output.txt
│   │   ├── stderr
│   │   └── stdout
│   ├── 34.150.138.100_6001_e-a57e7662-07fd-41bd-9fa4-c0d0b5d14f94.tgz
│   ├── 35.245.247.85_6001_e-65d12831-115f-4660-8d4f-36d16a162de4
│   │   ├── exitCode
│   │   ├── output_custom
│   │   ├── stderr
│   │   └── stdout
│   └── 35.245.247.85_6001_e-65d12831-115f-4660-8d4f-36d16a162de4.tgz
├── stderr
└── stdout

6 directories, 13 files
```
