### ISSUE TITLE
Better errors on job version

### ISSUE THREAD

**Issue by aronchick** [bacalhau-project/bacalhau#3719]
```
❯ bacalhau job run job.yaml
the job provided is invalid: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go struct field Job.Version of type uint64
```

This error is very hard to understand. What should the version be? And why would we tell someone what unmarshalling is?

**Comment by wdbaruni** [comment]
the job version is auto generated and updated by the requester node and should be ignored if it was provided by the user. This is a bug and should be handled better

**Comment by frrist** [comment]
> cannot unmarshal string into Go struct field Job.Version of type uint64

@aronchick can you share the `job.yaml` file you used? And in the future for errors like this please always share the corresponding file :smile: 

> the job version is auto generated and updated by the requester node and should be ignored if it was provided by the user. This is a bug and should be handled better

Hummm, on the other hand I think there is value to alerting users they are providing a field that has no affect/shouldn't be specified - else they may continue to do it and not realize its a noop, basically a waste of their time and increased cogitative  overhead. 
Better, we should exclude fields used by the protocol/internally from the data users submit

**Comment by wdbaruni** [comment]
fair enough. I think the benefit I was looking for is allowing users to submit a similar version of a job by doing something like `bacalhau job describe --output yaml | bacalhau job run`

**Comment by aronchick** [comment]
Agreed - but I think it's perfectly valid to just ignore and alert the user as a warning "hey we ignored this field"

**Comment by wdbaruni** [comment]
I like the warning approach instead of failing or silently ignoring the fields

**Comment by frrist** [comment]
I've created an issue to track separating user submission from system representation here: https://github.com/bacalhau-project/bacalhau/issues/3983

**Comment by wdbaruni** [comment]
@frrist lets just ignore system defined fields such as `version` for now

**Comment by frrist** [comment]
One way to reproduce this error is with the following job spec:
```yaml
Name: A Simple Docker Job
Type: batch
Version: "10"
Count: 1
Tasks:
  - Name: My main task
    Engine:
      Type: docker
      Params:
        Image: ubuntu:latest
        Entrypoint:
          - /bin/bash
        Parameters:
          - -c
          - echo Hello Bacalhau!
```
The key thing here is that `Version` is of type `string` which doesn't decode into the expected `int64` type of the job structure. However, the same spec with `Version` as an int runs just fine; the field is ignored. Similar behavior applies to `State`, `Revision`, `CreateTime` and `ModifyTime`. 
The main problem here is that we are decoding the job file provided by users into the `models.Job` type before performing validation. If this decoding fails we get (obtuse) validation errors from the marshaller, rather than the validation code.

I think there are several ways we can address this:
1. Validate the input from users against a [schema](https://github.com/bacalhau-project/bacalhau/pull/4074) before unmarshalling into a job.
2. Marshal the input from users into a `map[string]interface` and make assertions on the keys present e.g.:
```go
func PreValidate(jobSpec map[string]interface{}) error {
	disallowedKeys := map[string]struct{}{
		"id":         {},
		"state":      {},
		"version":    {},
		"revision":   {},
		"createtime": {},
		"modifytime": {},
	}

	var mErr error
	for key := range jobSpec {
		specKey := strings.ToLower(key)
		if _, found := disallowedKeys[specKey]; found {
			mErr = errors.Join(mErr, fmt.Errorf("%s field not allowed", key))
		}
	}
	return mErr
}
```
3. Write a custom marshallers for the job type

I prefer option 1 since 3 is a lot of work to maintain, and 2 won't catch other issues, such as when fields like `Count` are mistyped:
```yaml
Name: A Simple Docker Job
Type: batch
Count: "1"
Tasks:
  - Name: My main task
    Engine:
      Type: docker
      Params:
        Image: ubuntu:latest
        Entrypoint:
          - /bin/bash
        Parameters:
          - -c
          - echo Hello Bacalhau!
```
calling `bacalhau job run` with the above spec produces the error message:
`the job provided is invalid: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go struct field Job.Count of type int` which option 2 won't be able to catch.

@wdbaruni how would you like us to address this issue?
