### ISSUE TITLE
Job stuck in "Running" State?

### ISSUE THREAD

**Issue by aronchick** [bacalhau-project/bacalhau#4197]
I don't know how i got here.

Job spec:
```
Constraints: []
Labels: {}
Count: 1
Namespace: default
Priority: 0
Tasks:
  - Engine:
      Params:
        Image: docker.io/bacalhauproject/stress-ng:0.0.2
        Parameters:
          - "--cpu"
          - "2"
          - "--timeout"
          - "60"
        WorkingDirectory: ""
      Type: docker
    Name: main
    Network:
      Type: None
    Publisher:
      Type: ""
    Resources: {}
    Timeouts:
      ExecutionTimeout: 600
      QueueTimeout: 600
Type: batch
```

```
❯ bacalhau job describe j-6a7ed0b8
ID            = j-6a7ed0b8-48c3-453d-bdfc-2d7362611488
Name          = j-6a7ed0b8-48c3-453d-bdfc-2d7362611488
Namespace     = default
Type          = batch
State         = Running
Count         = 1
Created Time  = 2024-07-02 17:29:30
Modified Time = 2024-07-02 17:29:44
Version       = 0

Summary
Completed = 1

Job History
 TIME                 REV.  STATE    TOPIC       EVENT
 2024-07-02 17:29:30  1     Pending  Submission  Job submitted
 2024-07-02 17:29:44  2     Running

Executions
 ID          NODE ID     STATE      DESIRED  REV.  CREATED  MODIFIED   COMMENT
 e-c720091f  n-589109c0  Completed  Stopped  6     7h ago   6h22m ago  Accepted job

Execution e-c720091f History
 TIME                 REV.  STATE              TOPIC            EVENT
 2024-07-02 17:29:30  1     New
 2024-07-02 17:29:31  2     AskForBid
 2024-07-02 17:29:31  3     AskForBidAccepted  Requesting Node  Accepted job
 2024-07-02 17:29:44  4     AskForBidAccepted
 2024-07-02 17:29:44  5     BidAccepted
 2024-07-02 18:08:10  6     Completed

Standard Output
stress-ng: info:  [1] setting to a 1 min, 0 secs run per stressor
stress-ng: info:  [1] dispatching hogs: 2 cpu
stress-ng: info:  [1] skipped: 0
stress-ng: info:  [1] passed: 2: cpu (2)
stress-ng: info:  [1] failed: 0
stress-ng: info:  [1] metrics untrustworthy: 0
stress-ng: info:  [1] successful run completed in 1 min, 0.01 secs

```

```
❯ bacalhau node describe n-589109c0
Connection: CONNECTED
Info:
  BacalhauVersion:
    BuildDate: "0001-01-01T00:00:00Z"
    GOARCH: ""
    GOOS: ""
    GitCommit: ""
    GitVersion: ""
  ComputeNodeInfo:
    AvailableCapacity:
      CPU: 0.8
      Disk: 22845820108
      Memory: 2851392716
    EnqueuedExecutions: 0
    ExecutionEngines:
    - docker
    - wasm
    MaxCapacity:
      CPU: 0.8
      Disk: 22845820108
      Memory: 2851392716
    MaxJobRequirements:
      CPU: 0.8
      Disk: 22845820108
      Memory: 2851392716
    Publishers:
    - local
    - noop
    QueueCapacity: {}
    RunningExecutions: 0
    StorageSources:
    - inline
    - urldownload
  Labels:
    Architecture: amd64
    Operating-System: linux
    count: "5"
  NodeID: n-589109c0-824e-4f50-8604-3c6a2839b434
  NodeType: Compute
Membership: APPROVED
```

Job is "running", but history says "completed" and the container is completed.
