### ISSUE TITLE
Decouple Bacalhau repo from the configuration file.

### ISSUE THREAD

**Issue by frrist** [bacalhau-project/bacalhau#4219]
- The configuration file MAY contain a field named `RepoPath` whose value configures where Bacalhau initializes/opens a repo. If no config file is provided, or one is provided and the field is not present, the default value `$HOME/.bacalhau` MUST be used.
- The configuration system MUST NOT contain the following fields (read: remove them):
  - `Node.User.KeyPath`
    - A Bacalhau repo MUST contain a file named `user.key` which stores this value. If the file is not present, Bacalhau MUST generate one on the user's behalf. If the file is present, it MUST be used. If the file contains invalid data, Bacalhau MUST fail to start.
  - `Node.User.InstallationID`
    - The value of this field MAY be stored in a file named `system_metadata.yaml`.
  - `Node.Metrics.EventTracerPath`
    - This value MUST be removed. (We may consider replacing it at a later date with a filesystem journal containing the events a Bacalhau node has seen.)
  - `Node.Update.CheckStatePath`
    - This value MUST be removed. The data previously contained by it MUST be kept in a file named `system_metadata.yaml`.
  - `Node.ExecutorPluginPath`
    - This value MUST be removed. Pluggable executors MUST be stored in `./bacalhau/compute/plugins/executors/`.
  - `Node.ComputeStoragePath`
    - This value MUST be removed. Compute storage MUST live in `/.bacalhau/compute/**`.
  - `Node.Compute.ExecutionStore.Path`
    - This value MUST be removed. Execution storage MUST live in `/.bacalhau/compute/executions/**`.
  - `Node.Requester.JobStore.Path`
    - This value MUST be removed. The job store MUST live in `/.bacalhau/orchestrator/state_bolt.db`.
  - `Node.Network.StoreDir`
    - This value MUST be removed. The network store MUST live in `./bacalhau/orchestrator/nats-store`.

The below defines the configuration schema that MUST be accepted by a Bacalhau node.

```yaml
# The directory used to store state and other persistent data.
# On compute nodes this is used to store execution data such as
# inputs, results and execution store. 
# On orchestrator nodes, the repo is also used to store the job store.
Repo: $HOME/.bacalhau

# What this node is named on the network. NOTE: this is not the node identity.
Name: "Bytey McByteface"

# How and where the node reports telemetry data
Telemetry:
  Logging:
    Level: Info
    Format: console
  Metrics:
    Endpoint: http://localhost:4318
  Traces:
    Endpoing: http://localhost:4318

# configures if and how frequently the node checks for updates.
UpdateCheck:
  Enabled: true
  Interval: 24h

# HTTP API configuration:
# When used by client, it connectes to address
# When used by
API:
  Address: http://0.0.0.0:1234 
  TLS:
    CertFile: ""
    KeyFile: ""
    CAFile: ""
    
# Configuration for api authentication and authorization on computer and/or orchestrator
Auth:
# TokensPath will always be $REPO_PATH/tokens.json 
# REMOVE TokensPath: /Users/whatever/.bacalhau/tokens.json
Methods:
  ClientKey:
    Type: challenge
AccessPolicyPath: ""

# A job template to be used as default values for all jobs submitted to the network by the client. NB: This config only applies to the client.
JobDefaults:
  batch:
    Priority*: 50
    Task:
      Resources:
        CPU: 500m
        Memory: 1Gb
      Publisher:
        Type: local
      Timeouts:
        TotalTimeout: 30m
  daemon:
	  Priority: 100
	  Task:
		  ...
		  
# Supported means to download a job by the client
Downloaders:
  Providers:
    IPFS:
      Enabled: true
      Timeout: 5m
      Endpoint: http://localhost:5001
    S3*:
      Enabled: true
      Timeout: 5m
      AccessKey:
      SecretKey:
    HTTP:
      Enabled: true
      Timeout: 5m
      # optional
      Headers:
        - Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        - X-Auth-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...

# Orchestrator node specific configuration
Orchestrator:
  # true to run the node as an orchestrator
  # Note: Replaces Node.Type
  Enabled: true

  # Configuration for compute node connections
  # Note: Replaces Node.Network
  Listen: 0.0.0.0:4222
  Advertise:
  TLS*: {}
  Authorization: {}

  # Clustering configuration for orchestrator node to connect with other orchestrators
  # Note: Replaces for Node.Network
  Cluster:
    Listen: 0.0.0.0:6222
    Advertise:
    TLS*: {}
    Authorization*: {}
    Peers: []

  # Node manager configuration, used to manage compute nodes connected to the orchestrator
  # Note: Replaces Node.Requester.ControlPlanSettings
  NodeManager:
    # Note: Replaces Node.NodeInfoStoreTTL
    GCThreshold: 24h # Garbage collection threshold for disconnect node data.
    GCInterval*: 10m  # Interval for running garbage collection.
    DisconnectTimeout: 1m # Timeout for considering a node disconnected.
    ManualApproval: false # Require manual approval for nodes to be eligible for scheduling.

  # Job store configuration
  StateStore:
    JobGCInterval*: 10m
    JobGCThreshold*: 24h
    EvalGCThreshold*: 1h
    Backend:
      Type: BoltDB
      Config: {} # config related to the backend type

  Scheduler:
    WorkerCount: 0 # default no. of cores
    HousekeepingInterval: 30s
    HousekeepingTimeoutBuffer: 2m

  EvaluationBroker:
    VisibilityTimeout: 1m
    MaxRetryCount: 10

  # WebUI configuration.
  # Node: Replaces Node.WebUI
  # TODO: Necessary config to enable running the WebUI as a separate service
  WebUI:
    Enabled: false
    Listen: 0.0.0.0:8483

# Compute node specific configuration
Compute:
  # true to run the node as a compute node
  # Note: Replaces Node.Type
  Enabled: true

  # Configuration for compute node connections to the orchestrator
  # Note: Replaces Node.Network
  Orchestrators: []
  TLS*: {}
  Authorization: {}

  # Note: Replaces Node.Compute.ClusterTimeouts
  Heartbeat:
    InfoUpdateInterval: 1m0s
    ResourceUpdateInterval: 30s
    Interval: 15s
  
  # Execution state configuration
  StateStore:
    ExecutionGCInterval*: 10m
    ExecutionGCThreshold*: 24h
    Backend:
      Type: BoltDB
      Config: {}
      
  ## All field below control which jobs a compute node bids on.

  # Note: Replaces Node.Labels
  Labels: {}

  # Override the auto-detected capacity of the node. If provided, the AllocatedCapacity will be ignored.
  # Note: Replaces Node.Compute.TotalResourceLimits
  TotalCapacity:
    cpu: 1
    memory: 1Gb
    disk: 1Gb
    gpu: 0
  # Define the percentage of the total capacity that can be allocated to jobs
  # Note: Today it is hardcoded at 80%
  AllocatedCapacity:
    cpu: 80%
    memory: 80%
    disk: 80%
    gpu: 100%

  # replaces the data locality job policy
  AcceptRemoteDataJobs: true     
  # replaces RejectStatelessJobs
  AcceptStatelessJobs: true
  AcceptNetworkedJobs: true
  MinJobExecutionTimeout: 0s
  MaxJobExecutionTimeout: 0s

  # Input sources configuration.
  # This configuration is mainly used by the compute node to fetch inputs for the jobs.
  InputSources:
	# Note: Timeout and size values are irrelvant - handle w/ job timeout and resources.
    # Configurations specific for each input source supported by the compute node.
    Providers:
      IPFS:
        Enabled: true
        Endpoint: http://localhost:5001
      S3:
        Enabled: false
        Endpoint: https://storage.googleapis.com
        # TODO we should not store sensitive data in the config file.
        AccessKey:
        SecretKey:
      Local:
      	Enabled: true
        # Volumes mounted to the compute node and available to the jobs
        # Note: Replaces Node.AllowListedLocalPaths
        Volumes:
          - Name: "data"
            Path: "/data"
          - Name: "content"
            Path: "/usr/kitty/toys/"
      HTTP:
      	Enabled: true
        Endpoint: https://SomeWebServer.com
        # optional
        Headers:
          - Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
          - X-Auth-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...

    # Publishers configuration.
    # This configuration is used by compute nodes to publish results of the jobs
    Publishers:
      # Configurations specific for each publisher supported by the network
      Providers:
        IPFS:
          Enabled: true
          Endpoint: http://localhost:5001
        S3:
          Enabled: false
          Endpoint: https://storage.googleapis.com
          # TODO we should not store sensitive data in the config file.
          AccessKey:
          SecretKey:
        Local:
          Enabled: true
          Volumes:
            - Name: "outputs"
              Path: "/outputs"
            - Name: "results"
              Path: "/usr/kitty/results/"
        HTTP:
          Enabled: false
          Endpoint: https://SomeWebServer.com
          # optional
          Headers:
            - Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
            - X-Auth-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...

    # Execution engines configuration
    # This configuration is used by the compute nodes to execute the jobs
    Executors:
      # Configurations specific for each engine supported by the node
      Providers:
        Docker:
          Enabled: true
          Endpoint: unix:///var/run/docker.sock
          # Note: Replaces Node.Compute.ManifestCache and Node.Requester.TagCache
          ManifestCache:
            Size: 1000
            Duration: 1h0m0s
            RefreshFrequency: 1h0m0s
        Wasm:
          Enabled: false
  
```
