### ISSUE TITLE
WASM gives error when there are no inputs

### ISSUE THREAD

**Issue by js-ts** [bacalhau-project/bacalhau#775]
Code: https://colab.research.google.com/drive/1VMQU1gACspRFsz-dH6RnICLWBypnUKee#scrollTo=2I4DHnt0Vzua 

```
RunOutput:
                        Stdout: 'TypeError: Cannot read property ''forEach'' of undefined'
                        StdoutTruncated: false
                        Stderr: ',1040,1150,1166,1089,1091,1208,996,1199,1025,915,881,1233,982,1001,1215,1174,1112,1219,901,1131,1331,1317,1220,905,1261,1299,1348,1327,1053,1027,980,1154,1075,1209,1111,1043,1094,1162,1174,1126,1220,1283,991,787,1128,1092,1099,1143,1049,1325,1279,1311,948,1008,1109,1065,804,1137,943,983,1108,1055,1011,966,1181,1037,1270,1158,1413,1056,1289,1024,1054,1062,1164,1343,1105,986,1048,1025,1244,1262,1125,1074,1100,1203,1208,1091,1071,1430,1211,1088,1145,1388,1106,936,1070,1399,1004,893,930,981,1262,987,1169,1250,1251,1376,1195,1247,1323,1042,822,1051,960,1334,1149,1309,1031,1185,1289,1249,1276,1308,1130,1076,1068,949,1027,1031,1059,988,1017,942,1077,938,1028,766,1038,1041,910,870,828,919,861,906,934,935,923,912,819,963,958,1015,1092,1047,1121,929,956,1023,1061,987,1207,1033,1127,1085,1141,1152,1078,1026,1067,1071,1e3,1023,957,1032,1035,928,1017,985,1002,942,1043,877,903,986,982,843,935,1068,982,906,883,909,1008,994,955,842,885,951,940,928,794,880,977,1137,969,1112,1013,997,1046,972,866,937,930,936,1030,1019,972,941,995,1003,923,913,1039,988,992,1026,1074,1057,977,1038,1087,1064,1154,1054,1008,946,1086,983,934,838,1034,1210,1229,1190,1131,1101,1015,942,1017,1034,1100,1045,1107,1083,1100,1231,1187,1021,997,998,943,1036,788,741,996,961,749,514,741,736,814,845,759,910,843,828,938,810,1044,1119,1018,1069,1081,1098,1146,922,1027,1015,1115,1019,1162,1018,1182,1076,1162,1118,1208,1062,1047,1057,1089,1061,1078,1059,878,818,939,925,837,1137,1124,1109,1032,541,416,491,1016,979,1171,1141,893,1025,1081,986,939,932,748,888,1020,1027,906,1044,1122,950,1031,1e3,1010,971,957,966,1023,1049,1014,1131,928,1011,828,968,954,944,1033,952,990,910,989,976,973,916,863,904,945,999,1048,1034,865,940,983,888,899,1050,985,993,940,784,988,829,818,839,992,924,999,1005,1060,949,1028,1e3,989,976,961,992,859,816,819,927,797,876,897,833,911,926,806,566,640,850,947,955,959,859,1130,983,424,768,1112,949,1176,1056,1193,987,1028,1188,1091,1099,1178,1077,1109,1158,1181,880,653,699,1023,911,1072,899,1072,1081,1193,977,1096,1185,947,1121,1163,1072,1137,986,1110,'
                        StderrTruncated: true
                        ExitCode: 7
                        RunnerError: 'exit code was not zero: 7'
```

Fixes
>    All inputs there need to be checked - also, can you fix so you can take any cased spec fields? Eg INPUTS vs Inputs vs inputs. It's super fragile right now for many reasons
